### PR TITLE
Updated gulp and vinyl dependencies

### PR DESCRIPTION
**Pull request by NailRusty**
Hi! I wanted to do [this](https://github.com/bespoyasov/scroller/issues/25) issue. I started off with removing `build` dir. But I couldn't do build via `gulp build`, because it doesn't work on node version 15+
I've updated dependencies and rewritten gulpfile, check please

How the project should be built in your understanding?
What to do with `scroller.d.ts`, if we want to delete `build` dir?

### CODE REVIEW

**Comment by bespoyasov** [comment]
Hey! Thanks a lot! 

I will check this out as soon as I can. Hope to get to it this week :–)

**Comment by bespoyasov** [comment]
As for the building flow and type annotations, I suppose we can safely place the annotations in the project sources directory.

I think the builder should minify the code before publishing to npm and maybe do some CSS postprocessing.

The target for the JS code should be ES2020 to avoid extra polyfilling. Also, maybe even we can switch to pure ESM without any builder at all but I’m not sure yet 🤔

As for the new project structure, we can keep all the sources in the ‘src’ dir. The target directory may be named smth like ‘dist’. It will be ignored by git but not npm, to allow importing CSS.

**Comment by bespoyasov** [comment]
LGTM.

How do we plan to continue? We can use this PR for the whole issue, or we can split the issue into many atomic PRs each of which will complete a subtack from the issue.

**Comment by NailRusty** [comment]
I think we can close this PR, if you accept all changes. I've done with last three tasks and now we need to decide what to do with ES2020. Seems like we need to refactor everything. 
We can continue discussion in issue thread, could you write your specific vision about ES2020?

**Comment by bespoyasov** [comment]
So cool! Thanks a lot, this is a huge help since I don't have enough time to actively maintain this :–)
I will review the code this week and merge the PR. And yeah, we can totally create a new PR for refactoring the code.

As for ES and refactoring, I suppose we can ship the module as a pure ESM (it's now trendy, lol). So basically we'll need 
- to remove all of the polyfills, 
- switch the build target to ES2020 (the browser support is fine-ish), 
- make `test` ignored by git and npm, 
- switch to CSS custom properties,
- see if we can completely remove gulp.

I will also think about keeping built versions of scripts and styles for using them via `<link>` and `<script>` with CDN. Right now it is more reasonable to get rid of those and just use npm.

**Comment by bespoyasov** [comment]
Merged it, thanks a lot for the help! 🥳

**Pull request merged**
